### ISSUE TITLE
Adding small charts isn't responsive on dashboard apps

### ISSUE THREAD

**Issue by elmerv** [solid-adventure/trivial-ui#19]
Was playing around with trivial-ui and noticed that adding more than 3 small-sized charts leads to apps going outside of screen boundaries. Device: 13-inch macbook

![Screen Shot 2023-12-07 at 12 06 53 PM](https://github.com/solid-adventure/trivial-ui/assets/20259244/aa8aa47f-1804-4a99-89e5-c1276d499e6f)
![Screen Shot 2023-12-07 at 12 16 47 PM](https://github.com/solid-adventure/trivial-ui/assets/20259244/ca1c3f57-1d57-4f93-83b8-2ca661fde6c7)

Steps to reproduce: 
1) Create a dashboard app
2) Create more than 3 small charts (might be more depending on screen size)

I expected the small apps to drop down after reaching the max after reaching screen boundary, but the apps kept being added to the right side.

**Comment by vgkids** [comment]
Yes. Probably a quick-fix of having those wrap to the next row would be beneficial.

The bigger fix is a layout system to allow control over the layout, and grid system to allow charts of any size / location, but that's more than we have bandwidth to tackle right now.

**Comment by vgkids** [comment]
Fixed in PR #33
