### ISSUE TITLE
RecoverPassword's email ResetPassword URL not generating properly

### ISSUE THREAD

**Issue by drowninginflowers** [solid-adventure/trivial-ui#25]
**Issue**
Users are unable to access the Reset Password page when attempting to recover from a lost password.
The email from `RecoverPassword` generates a malformed URL for the email which leads to a blank page
This is verified locally and in staging, but not in production

**To Recreate**
1. Click the "**Forgot Password?**" link on the sign in page (routes to `/recoverpassword`)
2. Enter `email` for a valid `user`
3. Attempt to use the URL in the email to access the `PasswordReset` page

**Comment by vgkids** [comment]
Thanks for documenting, this is high-priority. @drowninginflowers Can you provide the correct URL format the email should be sending?

**Comment by vgkids** [comment]
@drowninginflowers This is fixed via https://github.com/solid-adventure/trivial-api/pull/198, right? Please close if so.
