### ISSUE TITLE
Redirect_URL is incorrect on self-hosted

### ISSUE THREAD

**Issue by elmerv** [solid-adventure/trivial-ui#55]
The redirect_url is currently set to the hosted environment, even in a self-hosted context.
```
https://www.trivialapps.io/resetpassword
```
This results in the the reset password link to be in the following format:
```
https://{prod_url}/auth/password/edit.{user_id}?config=default&redirect_url=http://www.trivialapps.io/resetpassword&reset_password_token={token}
```
The redirect_url is set to the incorrect TRIVIAL_UI url. This will cause users to be redirectd to a blank page on trivialapps.io.

A suggestion to fix this issue would be to manually change the redirect_url or add a `REDIRECT_URL` variable in .env file and reference the env var in [RecoverPassword.vue](https://github.com/solid-adventure/trivial-ui/blob/bc1a9f2fca8b5eb46dd8e2ae3090548c71e91783/source/components/RecoverPassword.vue#L77C1-L78C1)

There are no steps to reproduce this error as there is a current error on [trivial-api](https://github.com/solid-adventure/trivial-api/issues/219#issue-2094698737) preventing this redirect to occur.

**Comment by vgkids** [comment]
Work in tandem with https://github.com/solid-adventure/trivial-api/issues/219#issue-2094698737
